config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'mall' => 'products#index', :as => :mall

  resources :products, only: [:show]

  get 'profile' => 'users#profile', :as => :profile

  resources :items, only: [:show]

  resources :materials do
    collection do
      get :categories
      get :brands
      get :products
    end
  end
  
  resources :orders do
    get :payment, :on => :member
  end

  resource :shopping_cart

  put 'checkout' => 'orders#new'

end

app/models/brand.rb
# == Schema Information
#
# Table name: brands
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Brand < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_many :products, :dependent => :destroy

  scope :by_category, -> id do
    if id.to_i == 0
      all
    else
      joins(:categories).where categories: {id: id}
    end
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_and_belongs_to_many :brands

  scope :by_brand, -> id do
    if id.to_i == 0
      all
    else
      joins(:brands).where brands: {id: id}
    end
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  name       :string
#  brand_id   :integer
#  sku        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ActiveRecord::Base
  belongs_to :brand

  has_many :categories, :through => :brand

  scope :category, -> id do
    id.blank? ? all : joins(:categories).where(categories: {id: id}) 
  end

  scope :brand, -> id { id.blank? ? all : where(brand_id: id) }
  
  scope :sku, -> v { where 'sku like ?', "%#{v}%" }

  def self.filter(hash)
    %i[category brand sku].inject(all) { |result, msg| send msg, hash[msg] }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper :application

  class_attribute :menu, instance_predicate: false

  class << self
    def active_menu(name)
      self.menu = name.to_sym
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  active_menu :material

  def index
    @categories = Category.all
    @brands = Brand.all
  end

  def new
    @categories = Category.all
    @brands = Brand.all
    render partial: 'material'
  end

  def destroy
    head 200
  end

  def categories
    @categories = Category.by_brand params[:brand]
    render json: @categories
  end

  def brands
    @brands = Brand.by_category params[:category]
    render json: @brands
  end

  def products
    @products = Product.filter params
    render partial: 'related_products', object: @products
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index

  end

  def show

  end

  def create
    redirect_to payment_order_path(:fake_id)
  end

  def payment

  end

  def new

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  active_menu :home
  
  def home
    
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  active_menu :mall
  
  def show
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  active_menu :cart

  def show

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_menu(name)
    controller.menu = name
  end

  def current_menu?(name)
    controller.menu.to_s == name.to_s
  end

  def nav_link(text, url, name:, **options)
    content_tag :li, class:  current_menu?(name) ? 'active' : '' do
      link_to url, options do
        concat text
        yield if block_given?
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>乐屋 | Lewoo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!--[if lt IE 9]>
    <%= javascript_include_tag 'html5shiv-printshiv' %>
    <%= javascript_include_tag 'respond' %>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="page-<%= controller.menu %>">
  <div class="container">
    <%= render 'shared/header' %>

    <main><%= yield %></main>

    <%= render 'shared/footer' %>
  </div>
</body>
</html>

app/views/materials/_material.html.erb
<tbody>
  <tr class="<%= cycle '', 'alt' %>">
    <td>
      <%= select_tag 'category', options_from_collection_for_select(@categories, :id, :name), include_blank: '请选择', class: 'selectpicker material-category', data: {width: 'auto', container: 'body'} %>
    </td>
    <td>
      <%= select_tag 'brand', options_from_collection_for_select(@brands, :id, :name), include_blank: '请选择', class: 'selectpicker material-brand', data: {width: 'auto', container: 'body'} %>
    </td>
    <td>
      <span class="selected-product"><!-- 瓷砖 <i class="caret"></i> --></span>
    </td>
    <td>
      <input name="sku" class="material-sku" type="text" />
    </td>
    <td class="text-gray">红色</td>
    <td>100</td>
    <td class="text-gray">个</td>
    <td>1平方两块砖</td>
    <td>100</td>
    <td class="text-gray">个</td>
    <td class="text-gray">￥20</td>
    <td class="text-gray">￥2000</td>
    <td>厨房</td>
    <td>补货</td>
    <td>
      <%= link_to material_path(:fake_id), remote: true, method: 'delete', class: 'remove-material-item', data: {confirm: '您确定要删除吗？'} do %>
        <%= fa_icon 'trash-o' %>
      <% end %>
    </td>
  </tr>

  <tr class="related-products">
    <td colspan="15"></td>
  </tr>
</tbody>

app/views/materials/_product.html.erb
<label>
  <input type="radio" class="hidden selected-image" name="<%= uuid %>" value="<%= product.id %>" data-name="<%= product.name %>" data-sku="<%= product.sku %>">
  <img class="owl-lazy" data-src="http://placehold.it/100?text=<%= product.name %>">
</label>

app/views/materials/_related_products.html.erb
<div class="inner-wrap owl-carousel owl-theme">
  <%= render partial: 'product', collection: related_products, locals: {uuid: SecureRandom.hex} %>
</div>

app/views/materials/index.html.erb
<div class="material-list table-responsive">
  <table class="table bg-gray material-table">
    <thead>
      <tr>
        <th>品类</th>
        <th>品牌</th>
        <th>商品</th>
        <th>Sku</th>
        <th>规格</th>
        <th>工程算<br>量数量</th>
        <th>工程算<br>量单位</th>
        <th>计算规则</th>
        <th>数量</th>
        <th>单位</th>
        <th>单价</th>
        <th>合计</th>
        <th>使用单位</th>
        <th>备注</th>
        <th></th>
      </tr>
    </thead>
    <% 7.times do %>
      <%= render 'material' %>
    <% end %>
  </table>
</div>

<%= link_to new_material_path, remote: true, class: 'btn btn-link btn-add-material' do %>
  <%= fa_icon 'plus-circle' %> 添加选定品类
<% end %>

app/views/orders/index.html.erb
<section class="box">
  <table>
    <tr>
      <td>订单号：1150704790002546</td>
      <td>李斌</td>
      <td>在线支付</td>
      <td>订单金额：78.00元</td>
    </tr>
    <tr class="border-row">
      <td>
        <%= fa_icon 'file-o' %> 状态：已出库
      </td>
      <td colspan="2">下单时间：2015年07月05日 08:32</td>
      <td>
        <%= link_to '订单详情', order_path(:fake_id), class: 'btn-brown' %>
      </td>
    </tr>
  </table>
  <ul class="product-list list-unstyled">
    <% 2.times do %>
      <li>
        <%= link_to product_path(:fake_id) do %>
          <%= image_tag 'http://placehold.it/100?text=缩略图', class: 'img-thumbnail' %>
        <% end %>
        <p>
         <%= link_to '科勒水槽', product_path(:fake_id) %> 29元*1
        </p>
      </li>
    <% end %>
  </ul>
</section>

<section class="box">
  <table>
    <tr>
      <td>订单号：1150704790002546</td>
      <td>李斌</td>
      <td>在线支付</td>
      <td>订单金额：78.00元</td>
    </tr>
    <tr class="border-row">
      <td>
        <%= fa_icon 'file-o' %> 状态：已收货（包裹1）
      </td>
      <td colspan="2">收货时间：2015年07月05日 08:32</td>
      <td>
        包裹金额：<span class="text-yellow">2170.00元</span>
      </td>
    </tr>
  </table>
  <ul class="product-list list-unstyled">
    <% 2.times do %>
      <li>
        <%= link_to product_path(:fake_id) do %>
          <%= image_tag 'http://placehold.it/100?text=缩略图', class: 'img-thumbnail' %>
        <% end %>
        <p>
         <%= link_to '科勒水槽', product_path(:fake_id) %> 29元*1
        </p>
      </li>
    <% end %>
  </ul>
  <table>
    <tr class="border-row">
      <td>
        <%= fa_icon 'file-o' %> 状态：已收货（包裹2）
      </td>
      <td colspan="2">收货时间：2015年07月05日 08:32</td>
      <td>
        包裹金额：<span class="text-yellow">2170.00元</span>
      </td>
    </tr>
  </table>
  <ul class="product-list list-unstyled">
    <li>
      <%= link_to product_path(:fake_id) do %>
        <%= image_tag 'http://placehold.it/100?text=缩略图', class: 'img-thumbnail' %>
      <% end %>
      <p>
       <%= link_to '科勒水槽', product_path(:fake_id) %> 29元*1
      </p>
    </li>
  </ul>
</section>

app/views/orders/new.html.erb
<%= form_tag orders_path, method: 'post' do %>
  <dl class="checkout-box">
    <dt>收货地址</dt>
    <dd>
      <p>上海市浦东新区春晓路18号</p>
      <p>李斌 138 2239 3213</p>
    </dd>
  </dl>

  <dl class="checkout-box">
    <dt>发票信息</dt>
    <dd>
      <ul class="invoice-list list-unstyled">
        <li>
          <label>
            <input type="checkbox"> 开具发票 发票抬头：个人
          </label>
        </li>
        <li>
          <label>
            <input type="checkbox"> 开具发票 发票抬头：公司
          </label>
        </li>
      </ul>
      <a href="#" class="text-yellow btn-edit-invoice">修改</a>
    </dd>
  </dl>

  <dl class="checkout-box">
    <dt>确认装修公司</dt>
    <dd>
      <ul class="verify-list list-unstyled">
        <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam, consectetur!</li>
        <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et rem, corrupti aliquam blanditiis.</li>
        <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis, delectus, fugit. Molestias maiores velit fugiat voluptates.</li>
        <li>
          <label>
            <input type="checkbox"> 确认以上信息正确无误
          </label>
        </li>
      </ul>
    </dd>
  </dl>

  <div class="table-responsive">
    <table class="table bg-gray">
      <thead>
        <tr>
          <th>商品信息</th>
          <th>单价（元）</th>
          <th>数量</th>
          <th>小计（元）</th>
        </tr>
      </thead>
      <tbody>
        <% 2.times do %>
          <tr>
            <td class="product-item">
              <%= link_to product_path(:fake_id) do %>
                <%= image_tag 'http://placehold.it/100?text=缩略图', class: 'img-thumbnail' %>
              <% end %>
              <p>
                <%= link_to '科勒水槽', product_path(:fake_id) %> 套餐：A
              </p>
            </td>
            <td>421</td>
            <td>2</td>
            <td>842元</td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="4" class="text-right">
            商品总价：<i class="text-yellow">￥1021.00</i>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>

  <dl class="checkout-box">
    <dt>配送方式</dt>
    <dd>
      <ul class="shipment-list list-unstyled">
        <li>
          <label><input type="radio"> 尽快发货</label>
        </li>
        <li>
          <label><input type="radio"> 按装修公司设定批次自动选择发货时间</label>
          <ol>
            <li>
              第一批
              <div class="input-group pull-right date" data-provide="datepicker" data-date-format="dd/mm/yyyy">
                <input type="text" class="form-control">
                <span class="input-group-btn">
                  <button class="btn btn-default" type="button"><%= fa_icon 'calendar' %></button>
                </span>
              </div>
            </li>
            <li>
              第二批
              <div class="input-group pull-right date" data-provide="datepicker" data-date-format="dd/mm/yyyy">
                <input type="text" class="form-control">
                <span class="input-group-btn">
                  <button class="btn btn-default" type="button"><%= fa_icon 'calendar' %></button>
                </span>
              </div>
            </li>
            <li>
              第三批
              <div class="input-group pull-right date" data-provide="datepicker" data-date-format="dd/mm/yyyy">
                <input type="text" class="form-control">
                <span class="input-group-btn">
                  <button class="btn btn-default" type="button"><%= fa_icon 'calendar' %></button>
                </span>
              </div>
            </li>
          </ol>
        </li>
      </ul>
    </dd>
  </dl>

  <input type="submit" class="btn-brown" value="提交订单">
<% end %>

app/views/pages/home.html.erb
<div class="owl-carousel owl-theme one-item-slide">
  <% 4.times do |idx| %>
    <div>
      <%= link_to 'javascript:void(0)' do %>
        <%= image_tag "http://placehold.it/600x300?text=图片#{idx}" %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="time-limit-sale">
  <h3 class="title">限时秒杀</h3>
  <div class="row">
    <% 4.times do |i| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to product_path(:fake_id) do %>
            <%= image_tag 'http://placehold.it/250x300?text=展示图' %>
          <% end %>
          <div class="caption">
            <%= link_to '商品名称', product_path(:fake_id), class: 'truncate' %>
          </div>
          <div class="meta">
            <div>剩余时间：2小时53分钟2秒</div>
            <div class="prices">
              <span class="original-price">￥原价</span>
              <span class="sale-price">￥现价</span>
            </div>
            <%= link_to '立即购买', '#', class: 'btn-buy' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="brand">
  <h3  class="title">特价品牌</h3>
  <div class="row">
    <div class="col-md-6 col-md-push-6">
      <%= image_tag 'http://placehold.it/800x400?text=品牌图片', class: 'img-responsive' %>
    </div>
    <div class="col-md-6 col-md-pull-6">
      <dl>
        <dt class="brand-name">MUJI</dt>
        <dd>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit, est! Saepe sequi consequatur nemo, aperiam cum quod soluta dignissimos nulla deserunt, tempora debitis veniam excepturi? Perspiciatis debitis autem similique enim, hic minus vel dolorum odio earum, repellat sit quasi qui quidem ex sapiente fugit quam unde consequuntur, voluptate nisi temporibus commodi perferendis dignissimos error porro. Nesciunt cupiditate accusantium, molestiae vel expedita. Voluptate autem facilis laborum, eum minima, atque eius hic deleniti magni culpa perferendis ab animi! Corporis dolore accusantium nesciunt molestiae soluta, qui at repellat voluptate repudiandae quam, labore minus quod aliquam nisi ea asperiores reiciendis culpa modi. Quos, earum.</dd>
      </dl>
      <div>
        <em>8折优惠</em> <strong>20%</strong>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="row">
  <div class="col-sm-9 col-sm-push-3">

    <div class="row">
      <div class="col-sm-6 col-sm-offset-6">
        <%= render 'shared/search' %>
      </div>
    </div>

    <div class="row product-list">
      <% 12.times do |i| %>
        <div class="col-sm-4 col-md-3">
          <div class="thumbnail">
            <%= link_to product_path(:fake_id), class: "#{'newest-product' if i < 3}" do %>
              <%= image_tag 'http://placehold.it/768?text=展示图' %>
            <% end %>
            <div class="caption">
              <%= link_to '商品名称', product_path(:fake_id), class: 'truncate' %>
            </div>
            <div class="prices">
              <span class="original-price">￥原价</span>
              <span class="sale-price">￥现价</span>

              <%= link_to '#', class: 'add-to-cart' do %>
                <%= fa_icon 'shopping-cart' %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="clearfix">
      <nav class="pull-right">
        <ul class="pagination">
          <li>
            <a href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          <li class="active"><a href="#">1</a></li>
          <li><a href="#">2</a></li>
          <li><a href="#">3</a></li>
          <li><a href="#">4</a></li>
          <li><a href="#">5</a></li>
          <li>
            <a href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </div>

  <div class="col-sm-3 col-sm-pull-9">
    <%= render 'shared/sidebar' %>
  </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-push-8">
    <%= render 'shared/search' %>
  </div>
</div>

<div class="exhibit-images clearfix">
  <ul class="pgwSlider">
    <% 3.times do |i| %>
      <% idx = i + 1 %>
      <li>
        <%= image_tag "http://placehold.it/300x200?text=缩略图#{idx}", alt: '', data:{'large-src' => "http://placehold.it/1000x750?text=大图#{idx}"} %>
      </li>
    <% end %>
  </ul>
</div>

<script type="text/javascript">
  $('.pgwSlider').pgwSlider({autoSlide: false});
</script>

<form action="/shopping_cart" method="get" class="product-meta clearfix">
  <h3 class="title">商品名称</h3>

  <dl>
    <dt>价格</dt>
    <dd>
      <span class="original-price">原价</span>
      <span class="sale-price">现价</span>
    </dd>
  </dl>

  <dl>
    <dt>种类</dt>
    <dd>
      <label><input type="radio" name="type"><span>种类一</span></label>
      <label><input type="radio" name="type" checked><span>种类二</span></label>
      <label><input type="radio" name="type"><span>种类三</span></label>
    </dd>
  </dl>
  
  <dl>
    <dt>颜色</dt>
    <dd>
      <label><input type="radio" name="color" checked><span>颜色一</span></label>
      <label><input type="radio" name="color"><span>颜色二</span></label>
      <label><input type="radio" name="color"><span>颜色三</span></label>
    </dd>
  </dl>

  <dl>
    <dt>数量</dt>
    <dd>
      <div class="input-group">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button"><%= fa_icon 'minus' %></button>
        </span>
        <input type="text" class="form-control" value="1">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button"><%= fa_icon 'plus' %></button>
        </span>
      </div>
    </dd>
  </dl>
  <button class="btn-round pull-right" type="submit">加入购物车</button>
</form>

<div class="product-detail">
  <h3 class="title">商品参数</h3>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th>产品材料</th>
        <td>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas, consequuntur!</td>
      </tr>
      <tr>
        <th>表面做工</th>
        <td>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</td>
      </tr>
      <tr>
        <th>制造工艺</th>
        <td>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam?</td>
      </tr>
      <tr>
        <th>产品特点</th>
        <td>Lorem ipsum dolor sit amet, consectetur.</td>
      </tr>
      <tr>
        <th>产品标准</th>
        <td>Lorem ipsum dolor sit amet, consectetur adipisicing.</td>
      </tr>
      <tr>
        <th>选定列表</th>
        <td>Lorem ipsum dolor sit amet, consectetur adipisicing.</td>
      </tr>
    </tbody>
  </table>
</div>

<div class="recommendation">
  <h3 class="title">推荐</h3>
  <div class="owl-carousel owl-theme">
    <% 5.times do %>
      <%= link_to product_path(:fake_id) do %>
        <figure>
          <%= image_tag 'http://placehold.it/200?text=展示图' %>
          <figcaption>￥价格</figcaption>
        </figure>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer-wrap">
  <div class="row">
    <div class="col-sm-4">
      <h4>关于我们</h4>
      <ul class="list-unstyled">
        <li><a href="#">公司简介</a></li>
        <li><a href="#">资本支持</a></li>
        <li><a href="#">关于我们</a></li>
      </ul>
    </div>

    <div class="col-sm-4">
      <h4>联系方式</h4>
      <ul class="list-unstyled">
        <li>上海市浦东新区张江高科技园区999号</li>
        <li>电话：13312341234</li>
        <li>电子邮件：kefu@lewoo.com</li>
      </ul>
    </div>

    <div class="col-sm-4">
      <h4>合作伙伴</h4>
      <ul class="list-unstyled">
        <li><a href="#">XXX</a></li>
        <li><a href="#">YYY</a></li>
        <li><a href="#">ZZZ</a></li>
      </ul>
    </div>
  </div>
  <p>&copy; 2015 Lewoo &reg; The new way to design your home &trade;</p>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navigation navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav_links" aria-expanded="false">
        <span class="sr-only">切换导航菜单</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Lewoo</a>
    </div>
    
    <div class="avatar-menu dropdown pull-right">
      <a href="#" class="avatar dropdown-toggle" data-toggle="dropdown"><%= fa_icon :user %></a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to '个人中心', profile_path %>
        </li>
        <li><a href="#">消息 <span class="badge pull-right">4</span></a></li>
        <li><a href="#">退出</a></li>
      </ul>
    </div>
  
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse pull-right" id="nav_links">
      <ul class="nav navbar-nav">
        <%= nav_link '首页', root_path, name: 'home' %>
        <%= nav_link '商城', mall_path, name: 'mall' %>
        <%= nav_link '购物车', shopping_cart_path, name: 'cart', class: 'cart-link' do %>
          <strong style="font-size: 10px">2</strong>
        <% end %>
        <%= nav_link '主材包', materials_path, name: 'material' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
</header>

app/views/shopping_carts/show.html.erb
<h4 class="cart-title">全部商品</h4>

<%= form_tag checkout_path, method: 'put' do %>
  <div class="table-responsive">
    <table class="table bg-gray">
      <thead>
        <tr>
          <th></th>
          <th>商品信息</th>
          <th>单价（元）</th>
          <th>数量</th>
          <th>小计（元）</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <% 2.times do %>
          <tr>
            <td class="text-center">
              <input type="checkbox">
            </td>
            <td class="product-item">
              <%= link_to product_path(:fake_id) do %>
                <%= image_tag 'http://placehold.it/100?text=缩略图', class: 'img-thumbnail' %>
              <% end %>
              <p>
                <%= link_to '科勒水槽', product_path(:fake_id) %> 套餐：A
              </p>
            </td>
            <td>421</td>
            <td>
              <div class="input-group">
                <span class="input-group-btn">
                  <button class="btn btn-default" type="button"><%= fa_icon 'minus' %></button>
                </span>
                <input type="text" class="form-control product-count" value="2">
                <span class="input-group-btn">
                  <button class="btn btn-default" type="button"><%= fa_icon 'plus' %></button>
                </span>
              </div>
            </td>
            <td>842元</td>
            <td>
              <%= link_to '#', class: 'remove-cart-item' do %>
                <%= fa_icon 'trash' %>
              <% end %>
            </td>
          </tr>
        <% end %>
        <tr class="blank">
          <td colspan="6"></td>
        </tr>
      </tbody>
      <tfoot>
        <tr>
          <td class="text-center"><input type="checkbox"></td>
          <td>全选</td>
          <td colspan="4" class="text-right">
            已选商品 3 件
            <span class="cart-amount">合计：<i class="text-yellow">￥1021.00</i></span>
            <input type="submit" value="结算" class="btn-brown">
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
<% end %>

app/views/users/profile.html.erb
<div class="row">
  <div class="col-sm-9 col-sm-push-3">
    <div class="personal-info">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <%= image_tag 'http://placehold.it/120?text=头像', class: 'img-circle avatar' %>
          <ul class="list-unstyled">
            <li><label>姓名</label><span>李斌</span></li>
            <li><label>性别</label><span>男</span></li>
            <li><label>积分</label><span>1200</span></li>
            <li><label>手机号</label><span>132 3235 6478</span></li>
            <li><label>邮箱</label><span>abcd@qq.com</span></li>
          </ul>
          <a href="#" class="btn-round btn-edit-profile">编辑/查看个人信息</a>
        </div>
      </div>
    </div>

    <div class="item-list">
      <h5>我的装修项目列表</h5>

      <div class="item">
        <p class="state"><%= fa_icon 'file-o' %> 状态：已废弃</p>
        <ul class="list-unstyled">
          <li>装修公司：乐屋家装有限公司</li>
          <li>装修地址：上海市浦东新区春晓路80号</li>
          <li>项目经理：Leon</li>
          <li>设计师：Matt</li>
        </ul>
        <%= link_to '点击查看详情', item_path(:fake_id) %>
      </div>

      <div class="item">
        <p class="state"><%= fa_icon 'file-o' %> 状态：进行中</p>
        <ul class="list-unstyled">
          <li>装修公司：乐屋家装有限公司</li>
          <li>装修地址：上海市浦东新区春晓路80号</li>
          <li>项目经理：Leon</li>
          <li>设计师：Matt</li>
        </ul>
        <%= link_to '点击查看详情', item_path(:fake_id) %>
      </div>
    </div>
  </div>

  <div class="col-sm-3 col-sm-pull-9">
    <div class="profile-sidebar">
      <h5>个人中心</h5>
      <ul class="list-unstyled">
        <li>
          <%= link_to '我的装修', profile_path %>
        </li>
        <li>
          <%= link_to '我的订单', orders_path %>
        </li>
        <li>
          <%= link_to '我的资料', '#' %>
        </li>
      </ul>
    </div>
  </div>
</div>